version: '3.8'
services:
 db:
   container_name: postgres_container
   image: postgres
   restart: always
   environment:
     POSTGRES_DB: postgres_db
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: secret
     PGDATA: /var/lib/postgresql/data
   ports:
     - "5432:5432"
   networks:
     - docker-ufie
   volumes:
     - db-data:/var/lib/postgresql/data

 pgadmin:
   container_name: pgadmin4
   image: truecharts/pgadmin4
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@admin.com
     PGADMIN_DEFAULT_PASSWORD: secret
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "8080:80"
   networks:
     - docker-ufie    
   volumes:
     - pgadmin-data:/var/lib/pgadmin
volumes:
 db-data:
 pgadmin-data:

networks:
  docker-ufie:
    name: docker-ufie
    driver: bridge
    attachable: true
