version: "3"
services:
  app:
    image: nocobase/nocobase:0.8.0-alpha.13
    
    environment:
      - DB_DIALECT=mysql
      - DB_HOST=192.168.32.7
      - DB_DATABASE=nocobase
      - DB_USER=nocobase
      - DB_PASSWORD=password
      - LOCAL_STORAGE_BASE_URL=/storage/uploads
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "13000:80"
networks:
  default:
    name: docker-ufie
    external: true